parameters:
    mon_parameter: ma_valeur
services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - %locale%
            - 50